[features]
seeds = false
skip-lint = true

[programs.localnet]
swap_v2 = "CEhCJXXujkPiNGhfdFZWBJxWVApxqmhxgjsEC1StoKCV"

[programs.mainnet]
swap_v2 = "CEhCJXXujkPiNGhfdFZWBJxWVApxqmhxgjsEC1StoKCV"
serum_dex = { address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin", path = "./deps/serum-dex/dex/target/deploy/serum_dex.so" }

[[test.genesis]]
address ="B5ytTSxaVr9g4VSrnm6mWjMM4PHucFVvq1CforZiGCm7"
program = "./deps/serum-dex/dex/target/deploy/serum_dex.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
